name: hack_yeah_2k24
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_hooks: ^0.20.5
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4

  # Data Classes
  freezed_annotation: ^2.4.4

  # Dependency injection
  get_it: ^7.7.0
  injectable: ^2.4.4

  # UI
  gap: ^3.0.1
  cached_network_image: ^3.4.0

  # Navigation
  auto_route: ^9.1.0

  # Network
  retrofit: ^4.4.1

  # ENV
  flutter_dotenv: ^5.1.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  melos: ^6.1.0
  mason: ^0.1.0-dev.57
  mason_cli: ^0.1.0-dev.55
  build_runner: ^2.4.12
  freezed: ^2.5.7
  auto_route_generator: ^9.0.0
  retrofit_generator: ^9.1.2

flutter:
  uses-material-design: true
  generate: true
